# Generated by Django 4.2.2 on 2023-06-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambuadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhistory',
            name='requestingHospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_hospital', to='ambuadmin.hospital'),
        ),
    ]
