# Generated by Django 4.2.2 on 2023-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambuadmin', '0002_alter_operationhistory_requestinghospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalofficers',
            name='createdDate',
            field=models.DateField(auto_now=True),
        ),
    ]
